# Generated by Django 2.2.6 on 2020-02-01 08:07

from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('foto', models.FileField(upload_to=usuarios.models.get_file_path)),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('Eleitor', 'Eleitor'), ('Candidato', 'Candidato')], default='Eleitor', max_length=20)),
                ('curso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
        ),
    ]
