# Generated by Django 2.2.6 on 2020-01-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='tipo',
            field=models.CharField(choices=[(1, 'Administrador'), (2, 'Eleitor'), (2, 'Candidato')], default=1, max_length=50),
        ),
    ]
