# Generated by Django 2.2.6 on 2020-01-20 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cadastro_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('Eleitor', 'Eleitor'), ('Candidato', 'Candidato')], default='Eleitor', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
