# Generated by Django 2.2.6 on 2020-01-26 10:31

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(upload_to=usuarios.models.get_file_path),
        ),
    ]
