# Generated by Django 2.2.6 on 2020-01-20 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('centro', models.CharField(max_length=50)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
