# Generated by Django 2.2.6 on 2020-02-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
                ('tipo', models.CharField(choices=[('eleicao', 'Eleição'), ('votacao', 'Votação')], default='Eleição', max_length=20)),
            ],
        ),
    ]
